//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 

namespace SlutPriser {
/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class Item
{

    private string salesTitleField;

    private string salesTextField;

    private string salesTextShortField;

    private string propertyDesignationField;

    private string sellerChangeDateField;

    private string floorField;

    private string elevatorField;

    private string elevatorCommentField;

    private string builtField;

    private string bidCodeField;

    private string acquisitionField;

    private string builtCommentField;

    private string energyCertificateDateField;

    private string energyConsumptionField;

    private string apartmentNumberField;

    private string apartmentNumberLmvField;

    private string inspectedDateField;

    private string windowField;

    private string balconyField;

    private string storageroomField;

    private string fireplaceField;

    private string tvInternetField;

    private string districtField;

    private string extraContactPersonsField;

    private string biddersField;

    private string localField;

    private string commercialField;

    private string businessSpaceField;

    private string includedField;

    private ItemLocation[] locationField;

    private ItemEconomy[] economyField;

    private ItemSize[] sizeField;

    private ItemPlanRegulations[] planRegulationsField;

    private ItemEnergy[] energyField;

    private ItemDescriptionsDescription[] descriptionsField;

    private ItemPart[] partField;

    private ItemPartFee[] partFeeField;

    private ItemAssociation[] associationField;

    private ItemBuilding[] buildingField;

    private ItemRealtorsRealtor[] realtorsField;

    private ItemShowings[] showingsField;

    private ItemBids[] bidsField;

    private ItemServitudes[] servitudesField;

    private ItemImagesImage[] imagesField;

    private ItemMediaMediaItem[] mediaField;

    private ItemObjectDocumentsObjectDocument[] objectDocumentsField;

    private ItemApartmentCooperativeDocumentsApartmentCooperativeDocument[] apartmentCooperativeDocumentsField;

    private ItemOffice[] officeField;

    private ItemCorporation[] corporationField;

    private ItemStatus[] statusField;

    private ItemMeta[] metaField;

    private string idField;

    private string orderNumberField;

    private string typeIdField;

    private string aliasField;

    private string statusField1;

    private string typeField;

    private string formOfOwnershipIdField;

    private string formOfOwnershipField;

    private string descUrlField;

    private string hemnetUrlField;

    private string modifiedAtField;

    private string insertedAtField;

    private string masterIdField;

    private string soldField;

    private string sortField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SalesTitle
    {
        get
        {
            return this.salesTitleField;
        }
        set
        {
            this.salesTitleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SalesText
    {
        get
        {
            return this.salesTextField;
        }
        set
        {
            this.salesTextField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SalesTextShort
    {
        get
        {
            return this.salesTextShortField;
        }
        set
        {
            this.salesTextShortField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PropertyDesignation
    {
        get
        {
            return this.propertyDesignationField;
        }
        set
        {
            this.propertyDesignationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SellerChangeDate
    {
        get
        {
            return this.sellerChangeDateField;
        }
        set
        {
            this.sellerChangeDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Floor
    {
        get
        {
            return this.floorField;
        }
        set
        {
            this.floorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Elevator
    {
        get
        {
            return this.elevatorField;
        }
        set
        {
            this.elevatorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ElevatorComment
    {
        get
        {
            return this.elevatorCommentField;
        }
        set
        {
            this.elevatorCommentField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Built
    {
        get
        {
            return this.builtField;
        }
        set
        {
            this.builtField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BidCode
    {
        get
        {
            return this.bidCodeField;
        }
        set
        {
            this.bidCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Acquisition
    {
        get
        {
            return this.acquisitionField;
        }
        set
        {
            this.acquisitionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BuiltComment
    {
        get
        {
            return this.builtCommentField;
        }
        set
        {
            this.builtCommentField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EnergyCertificateDate
    {
        get
        {
            return this.energyCertificateDateField;
        }
        set
        {
            this.energyCertificateDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EnergyConsumption
    {
        get
        {
            return this.energyConsumptionField;
        }
        set
        {
            this.energyConsumptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ApartmentNumber
    {
        get
        {
            return this.apartmentNumberField;
        }
        set
        {
            this.apartmentNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ApartmentNumberLmv
    {
        get
        {
            return this.apartmentNumberLmvField;
        }
        set
        {
            this.apartmentNumberLmvField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string InspectedDate
    {
        get
        {
            return this.inspectedDateField;
        }
        set
        {
            this.inspectedDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Window
    {
        get
        {
            return this.windowField;
        }
        set
        {
            this.windowField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Balcony
    {
        get
        {
            return this.balconyField;
        }
        set
        {
            this.balconyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Storageroom
    {
        get
        {
            return this.storageroomField;
        }
        set
        {
            this.storageroomField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Fireplace
    {
        get
        {
            return this.fireplaceField;
        }
        set
        {
            this.fireplaceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TvInternet
    {
        get
        {
            return this.tvInternetField;
        }
        set
        {
            this.tvInternetField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string District
    {
        get
        {
            return this.districtField;
        }
        set
        {
            this.districtField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ExtraContactPersons
    {
        get
        {
            return this.extraContactPersonsField;
        }
        set
        {
            this.extraContactPersonsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Bidders
    {
        get
        {
            return this.biddersField;
        }
        set
        {
            this.biddersField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Local
    {
        get
        {
            return this.localField;
        }
        set
        {
            this.localField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Commercial
    {
        get
        {
            return this.commercialField;
        }
        set
        {
            this.commercialField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BusinessSpace
    {
        get
        {
            return this.businessSpaceField;
        }
        set
        {
            this.businessSpaceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Included
    {
        get
        {
            return this.includedField;
        }
        set
        {
            this.includedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Location", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemLocation[] Location
    {
        get
        {
            return this.locationField;
        }
        set
        {
            this.locationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Economy", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemEconomy[] Economy
    {
        get
        {
            return this.economyField;
        }
        set
        {
            this.economyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Size", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemSize[] Size
    {
        get
        {
            return this.sizeField;
        }
        set
        {
            this.sizeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PlanRegulations", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemPlanRegulations[] PlanRegulations
    {
        get
        {
            return this.planRegulationsField;
        }
        set
        {
            this.planRegulationsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Energy", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemEnergy[] Energy
    {
        get
        {
            return this.energyField;
        }
        set
        {
            this.energyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Description", typeof(ItemDescriptionsDescription), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public ItemDescriptionsDescription[] Descriptions
    {
        get
        {
            return this.descriptionsField;
        }
        set
        {
            this.descriptionsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Part", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemPart[] Part
    {
        get
        {
            return this.partField;
        }
        set
        {
            this.partField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PartFee", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemPartFee[] PartFee
    {
        get
        {
            return this.partFeeField;
        }
        set
        {
            this.partFeeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Association", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemAssociation[] Association
    {
        get
        {
            return this.associationField;
        }
        set
        {
            this.associationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Building", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemBuilding[] Building
    {
        get
        {
            return this.buildingField;
        }
        set
        {
            this.buildingField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Realtor", typeof(ItemRealtorsRealtor), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public ItemRealtorsRealtor[] Realtors
    {
        get
        {
            return this.realtorsField;
        }
        set
        {
            this.realtorsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Showings", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemShowings[] Showings
    {
        get
        {
            return this.showingsField;
        }
        set
        {
            this.showingsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Bids", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemBids[] Bids
    {
        get
        {
            return this.bidsField;
        }
        set
        {
            this.bidsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Servitudes", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemServitudes[] Servitudes
    {
        get
        {
            return this.servitudesField;
        }
        set
        {
            this.servitudesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Image", typeof(ItemImagesImage), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public ItemImagesImage[] Images
    {
        get
        {
            return this.imagesField;
        }
        set
        {
            this.imagesField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("MediaItem", typeof(ItemMediaMediaItem), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public ItemMediaMediaItem[] Media
    {
        get
        {
            return this.mediaField;
        }
        set
        {
            this.mediaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ObjectDocument", typeof(ItemObjectDocumentsObjectDocument), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public ItemObjectDocumentsObjectDocument[] ObjectDocuments
    {
        get
        {
            return this.objectDocumentsField;
        }
        set
        {
            this.objectDocumentsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("ApartmentCooperativeDocument", typeof(ItemApartmentCooperativeDocumentsApartmentCooperativeDocument), Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = false)]
    public ItemApartmentCooperativeDocumentsApartmentCooperativeDocument[] ApartmentCooperativeDocuments
    {
        get
        {
            return this.apartmentCooperativeDocumentsField;
        }
        set
        {
            this.apartmentCooperativeDocumentsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Office", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemOffice[] Office
    {
        get
        {
            return this.officeField;
        }
        set
        {
            this.officeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Corporation", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemCorporation[] Corporation
    {
        get
        {
            return this.corporationField;
        }
        set
        {
            this.corporationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Status", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemStatus[] Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Meta", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemMeta[] Meta
    {
        get
        {
            return this.metaField;
        }
        set
        {
            this.metaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string orderNumber
    {
        get
        {
            return this.orderNumberField;
        }
        set
        {
            this.orderNumberField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string typeId
    {
        get
        {
            return this.typeIdField;
        }
        set
        {
            this.typeIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string alias
    {
        get
        {
            return this.aliasField;
        }
        set
        {
            this.aliasField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string status
    {
        get
        {
            return this.statusField1;
        }
        set
        {
            this.statusField1 = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string formOfOwnershipId
    {
        get
        {
            return this.formOfOwnershipIdField;
        }
        set
        {
            this.formOfOwnershipIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string formOfOwnership
    {
        get
        {
            return this.formOfOwnershipField;
        }
        set
        {
            this.formOfOwnershipField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string descUrl
    {
        get
        {
            return this.descUrlField;
        }
        set
        {
            this.descUrlField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hemnetUrl
    {
        get
        {
            return this.hemnetUrlField;
        }
        set
        {
            this.hemnetUrlField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string modifiedAt
    {
        get
        {
            return this.modifiedAtField;
        }
        set
        {
            this.modifiedAtField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string insertedAt
    {
        get
        {
            return this.insertedAtField;
        }
        set
        {
            this.insertedAtField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string masterId
    {
        get
        {
            return this.masterIdField;
        }
        set
        {
            this.masterIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sold
    {
        get
        {
            return this.soldField;
        }
        set
        {
            this.soldField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string sort
    {
        get
        {
            return this.sortField;
        }
        set
        {
            this.sortField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemLocation
{

    private string countryField;

    private string countryIdField;

    private string countryIsoCodeField;

    private string communeField;

    private string communeIdField;

    private string cityField;

    private string districtField;

    private string parishField;

    private string parishIdField;

    private string addressField;

    private string zipcodeField;

    private string xCoordinateField;

    private string yCoordinateField;

    private string latField;

    private string lonField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string country
    {
        get
        {
            return this.countryField;
        }
        set
        {
            this.countryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string countryId
    {
        get
        {
            return this.countryIdField;
        }
        set
        {
            this.countryIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string countryIsoCode
    {
        get
        {
            return this.countryIsoCodeField;
        }
        set
        {
            this.countryIsoCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string commune
    {
        get
        {
            return this.communeField;
        }
        set
        {
            this.communeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string communeId
    {
        get
        {
            return this.communeIdField;
        }
        set
        {
            this.communeIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string city
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string district
    {
        get
        {
            return this.districtField;
        }
        set
        {
            this.districtField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string parish
    {
        get
        {
            return this.parishField;
        }
        set
        {
            this.parishField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string parishId
    {
        get
        {
            return this.parishIdField;
        }
        set
        {
            this.parishIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string zipcode
    {
        get
        {
            return this.zipcodeField;
        }
        set
        {
            this.zipcodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string xCoordinate
    {
        get
        {
            return this.xCoordinateField;
        }
        set
        {
            this.xCoordinateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string yCoordinate
    {
        get
        {
            return this.yCoordinateField;
        }
        set
        {
            this.yCoordinateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lat
    {
        get
        {
            return this.latField;
        }
        set
        {
            this.latField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lon
    {
        get
        {
            return this.lonField;
        }
        set
        {
            this.lonField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemEconomy
{

    private ItemEconomyOperatingCosts[] operatingCostsField;

    private string priceField;

    private string currencyField;

    private string currencyIso4217Field;

    private string priceCommentField;

    private string secondaryPriceField;

    private string secondaryCurrencyField;

    private string secondaryCurrencyIso4217Field;

    private string secondaryPriceCommentField;

    private string taxHouseField;

    private string taxGroundField;

    private string taxFieldField;

    private string taxPastureField;

    private string taxForestField;

    private string taxForestImpedimentField;

    private string taxCommercialBuildingField;

    private string taxOtherField;

    private string taxSumField;

    private string taxTotalField;

    private string groundRentField;

    private string groundRentExpiryField;

    private string leaseField;

    private string taxYearField;

    private string valueYearField;

    private string feeField;

    private string repairFundField;

    private string includedInFeeField;

    private string excludedInFeeField;

    private string knownFeeChangeField;

    private string taxRateField;

    private string taxCodeField;

    private string taxCommentField;

    private string insuranceFullValueField;

    private string pledgedField;

    private string noOfPledgeField;

    private string pledgefeeField;

    private string transferfeeField;

    private string transferfeepaidbyField;

    private string taxPrelimField;

    private string totalMortgagesField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OperatingCosts", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemEconomyOperatingCosts[] OperatingCosts
    {
        get
        {
            return this.operatingCostsField;
        }
        set
        {
            this.operatingCostsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string price
    {
        get
        {
            return this.priceField;
        }
        set
        {
            this.priceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string currency
    {
        get
        {
            return this.currencyField;
        }
        set
        {
            this.currencyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string currencyIso4217
    {
        get
        {
            return this.currencyIso4217Field;
        }
        set
        {
            this.currencyIso4217Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string priceComment
    {
        get
        {
            return this.priceCommentField;
        }
        set
        {
            this.priceCommentField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string secondaryPrice
    {
        get
        {
            return this.secondaryPriceField;
        }
        set
        {
            this.secondaryPriceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string secondaryCurrency
    {
        get
        {
            return this.secondaryCurrencyField;
        }
        set
        {
            this.secondaryCurrencyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string secondaryCurrencyIso4217
    {
        get
        {
            return this.secondaryCurrencyIso4217Field;
        }
        set
        {
            this.secondaryCurrencyIso4217Field = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string secondaryPriceComment
    {
        get
        {
            return this.secondaryPriceCommentField;
        }
        set
        {
            this.secondaryPriceCommentField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string taxHouse
    {
        get
        {
            return this.taxHouseField;
        }
        set
        {
            this.taxHouseField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string taxGround
    {
        get
        {
            return this.taxGroundField;
        }
        set
        {
            this.taxGroundField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string taxField
    {
        get
        {
            return this.taxFieldField;
        }
        set
        {
            this.taxFieldField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string taxPasture
    {
        get
        {
            return this.taxPastureField;
        }
        set
        {
            this.taxPastureField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string taxForest
    {
        get
        {
            return this.taxForestField;
        }
        set
        {
            this.taxForestField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string taxForestImpediment
    {
        get
        {
            return this.taxForestImpedimentField;
        }
        set
        {
            this.taxForestImpedimentField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string taxCommercialBuilding
    {
        get
        {
            return this.taxCommercialBuildingField;
        }
        set
        {
            this.taxCommercialBuildingField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string taxOther
    {
        get
        {
            return this.taxOtherField;
        }
        set
        {
            this.taxOtherField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string taxSum
    {
        get
        {
            return this.taxSumField;
        }
        set
        {
            this.taxSumField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string taxTotal
    {
        get
        {
            return this.taxTotalField;
        }
        set
        {
            this.taxTotalField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string groundRent
    {
        get
        {
            return this.groundRentField;
        }
        set
        {
            this.groundRentField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string groundRentExpiry
    {
        get
        {
            return this.groundRentExpiryField;
        }
        set
        {
            this.groundRentExpiryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lease
    {
        get
        {
            return this.leaseField;
        }
        set
        {
            this.leaseField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string taxYear
    {
        get
        {
            return this.taxYearField;
        }
        set
        {
            this.taxYearField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string valueYear
    {
        get
        {
            return this.valueYearField;
        }
        set
        {
            this.valueYearField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fee
    {
        get
        {
            return this.feeField;
        }
        set
        {
            this.feeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string repairFund
    {
        get
        {
            return this.repairFundField;
        }
        set
        {
            this.repairFundField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string includedInFee
    {
        get
        {
            return this.includedInFeeField;
        }
        set
        {
            this.includedInFeeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string excludedInFee
    {
        get
        {
            return this.excludedInFeeField;
        }
        set
        {
            this.excludedInFeeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string knownFeeChange
    {
        get
        {
            return this.knownFeeChangeField;
        }
        set
        {
            this.knownFeeChangeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string taxRate
    {
        get
        {
            return this.taxRateField;
        }
        set
        {
            this.taxRateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string taxCode
    {
        get
        {
            return this.taxCodeField;
        }
        set
        {
            this.taxCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string taxComment
    {
        get
        {
            return this.taxCommentField;
        }
        set
        {
            this.taxCommentField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string insuranceFullValue
    {
        get
        {
            return this.insuranceFullValueField;
        }
        set
        {
            this.insuranceFullValueField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pledged
    {
        get
        {
            return this.pledgedField;
        }
        set
        {
            this.pledgedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string noOfPledge
    {
        get
        {
            return this.noOfPledgeField;
        }
        set
        {
            this.noOfPledgeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string pledgefee
    {
        get
        {
            return this.pledgefeeField;
        }
        set
        {
            this.pledgefeeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string transferfee
    {
        get
        {
            return this.transferfeeField;
        }
        set
        {
            this.transferfeeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string transferfeepaidby
    {
        get
        {
            return this.transferfeepaidbyField;
        }
        set
        {
            this.transferfeepaidbyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string taxPrelim
    {
        get
        {
            return this.taxPrelimField;
        }
        set
        {
            this.taxPrelimField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string totalMortgages
    {
        get
        {
            return this.totalMortgagesField;
        }
        set
        {
            this.totalMortgagesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemEconomyOperatingCosts
{

    private ItemEconomyOperatingCostsOperatingCost[] operatingCostField;

    private string commentField;

    private string numberOfPersonsField;

    private string totalAmountField;

    private string totalAmountYearField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OperatingCost", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemEconomyOperatingCostsOperatingCost[] OperatingCost
    {
        get
        {
            return this.operatingCostField;
        }
        set
        {
            this.operatingCostField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string comment
    {
        get
        {
            return this.commentField;
        }
        set
        {
            this.commentField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string numberOfPersons
    {
        get
        {
            return this.numberOfPersonsField;
        }
        set
        {
            this.numberOfPersonsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string totalAmount
    {
        get
        {
            return this.totalAmountField;
        }
        set
        {
            this.totalAmountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string totalAmountYear
    {
        get
        {
            return this.totalAmountYearField;
        }
        set
        {
            this.totalAmountYearField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemEconomyOperatingCostsOperatingCost
{

    private string aliasField;

    private string amountField;

    private string amountYearField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string alias
    {
        get
        {
            return this.aliasField;
        }
        set
        {
            this.aliasField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string amount
    {
        get
        {
            return this.amountField;
        }
        set
        {
            this.amountField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string amountYear
    {
        get
        {
            return this.amountYearField;
        }
        set
        {
            this.amountYearField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemSize
{

    private ItemSizeAreas[] areasField;

    private string roomsField;

    private string roomsInformationField;

    private string minRoomsField;

    private string maxRoomsField;

    private string minBedroomsField;

    private string maxBedroomsField;

    private string minAreaField;

    private string maxAreaField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Areas", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemSizeAreas[] Areas
    {
        get
        {
            return this.areasField;
        }
        set
        {
            this.areasField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string rooms
    {
        get
        {
            return this.roomsField;
        }
        set
        {
            this.roomsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string roomsInformation
    {
        get
        {
            return this.roomsInformationField;
        }
        set
        {
            this.roomsInformationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string minRooms
    {
        get
        {
            return this.minRoomsField;
        }
        set
        {
            this.minRoomsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxRooms
    {
        get
        {
            return this.maxRoomsField;
        }
        set
        {
            this.maxRoomsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string minBedrooms
    {
        get
        {
            return this.minBedroomsField;
        }
        set
        {
            this.minBedroomsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxBedrooms
    {
        get
        {
            return this.maxBedroomsField;
        }
        set
        {
            this.maxBedroomsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string minArea
    {
        get
        {
            return this.minAreaField;
        }
        set
        {
            this.minAreaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string maxArea
    {
        get
        {
            return this.maxAreaField;
        }
        set
        {
            this.maxAreaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemSizeAreas
{

    private ItemSizeAreasArea[] areaField;

    private string commentField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Area", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemSizeAreasArea[] Area
    {
        get
        {
            return this.areaField;
        }
        set
        {
            this.areaField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string comment
    {
        get
        {
            return this.commentField;
        }
        set
        {
            this.commentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemSizeAreasArea
{

    private string typeField;

    private string sizeField;

    private string unitField;

    private string basedOnField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string size
    {
        get
        {
            return this.sizeField;
        }
        set
        {
            this.sizeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string unit
    {
        get
        {
            return this.unitField;
        }
        set
        {
            this.unitField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string basedOn
    {
        get
        {
            return this.basedOnField;
        }
        set
        {
            this.basedOnField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemPlanRegulations
{

    private string dateField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string date
    {
        get
        {
            return this.dateField;
        }
        set
        {
            this.dateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemEnergy
{

    private string classField;

    private string performanceField;

    private string certificateDateField;

    private string energyDeclarationAddressField;

    private string statusField;

    private string electricitySupplierField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string @class
    {
        get
        {
            return this.classField;
        }
        set
        {
            this.classField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string performance
    {
        get
        {
            return this.performanceField;
        }
        set
        {
            this.performanceField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string certificateDate
    {
        get
        {
            return this.certificateDateField;
        }
        set
        {
            this.certificateDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string energyDeclarationAddress
    {
        get
        {
            return this.energyDeclarationAddressField;
        }
        set
        {
            this.energyDeclarationAddressField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string electricitySupplier
    {
        get
        {
            return this.electricitySupplierField;
        }
        set
        {
            this.electricitySupplierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemDescriptionsDescription
{

    private string titleField;

    private string contentField;

    private string categoryIdField;

    private string categoryField;

    private string languageCodeField;

    private string languageField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Title
    {
        get
        {
            return this.titleField;
        }
        set
        {
            this.titleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Content
    {
        get
        {
            return this.contentField;
        }
        set
        {
            this.contentField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string categoryId
    {
        get
        {
            return this.categoryIdField;
        }
        set
        {
            this.categoryIdField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string category
    {
        get
        {
            return this.categoryField;
        }
        set
        {
            this.categoryField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string languageCode
    {
        get
        {
            return this.languageCodeField;
        }
        set
        {
            this.languageCodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string language
    {
        get
        {
            return this.languageField;
        }
        set
        {
            this.languageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemPart
{

    private string feeField;

    private string percentField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Fee
    {
        get
        {
            return this.feeField;
        }
        set
        {
            this.feeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string percent
    {
        get
        {
            return this.percentField;
        }
        set
        {
            this.percentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemPartFee
{

    private string feeField;

    private string percentField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Fee
    {
        get
        {
            return this.feeField;
        }
        set
        {
            this.feeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string percent
    {
        get
        {
            return this.percentField;
        }
        set
        {
            this.percentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemAssociation
{

    private string genuineField;

    private string legalPersonAllowedField;

    private string landownersField;

    private string nameField;

    private string visitAddressField;

    private string webPageField;

    private string addressField;

    private string zipcodeField;

    private string cityField;

    private string mailField;

    private string phoneField;

    private string contactPersonNameField;

    private string contactPhoneField;

    private string propertyDesignitionField;

    private string propertyDescriptionField;

    private string xcoordinateField;

    private string ycoordinateField;

    private string phoneStringField;

    private string contactPhoneStringField;

    private string organizationNoField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string genuine
    {
        get
        {
            return this.genuineField;
        }
        set
        {
            this.genuineField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string legalPersonAllowed
    {
        get
        {
            return this.legalPersonAllowedField;
        }
        set
        {
            this.legalPersonAllowedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string landowners
    {
        get
        {
            return this.landownersField;
        }
        set
        {
            this.landownersField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string visitAddress
    {
        get
        {
            return this.visitAddressField;
        }
        set
        {
            this.visitAddressField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string webPage
    {
        get
        {
            return this.webPageField;
        }
        set
        {
            this.webPageField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string address
    {
        get
        {
            return this.addressField;
        }
        set
        {
            this.addressField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string zipcode
    {
        get
        {
            return this.zipcodeField;
        }
        set
        {
            this.zipcodeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string city
    {
        get
        {
            return this.cityField;
        }
        set
        {
            this.cityField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mail
    {
        get
        {
            return this.mailField;
        }
        set
        {
            this.mailField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string phone
    {
        get
        {
            return this.phoneField;
        }
        set
        {
            this.phoneField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string contactPersonName
    {
        get
        {
            return this.contactPersonNameField;
        }
        set
        {
            this.contactPersonNameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string contactPhone
    {
        get
        {
            return this.contactPhoneField;
        }
        set
        {
            this.contactPhoneField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string propertyDesignition
    {
        get
        {
            return this.propertyDesignitionField;
        }
        set
        {
            this.propertyDesignitionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string propertyDescription
    {
        get
        {
            return this.propertyDescriptionField;
        }
        set
        {
            this.propertyDescriptionField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string xcoordinate
    {
        get
        {
            return this.xcoordinateField;
        }
        set
        {
            this.xcoordinateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ycoordinate
    {
        get
        {
            return this.ycoordinateField;
        }
        set
        {
            this.ycoordinateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string phoneString
    {
        get
        {
            return this.phoneStringField;
        }
        set
        {
            this.phoneStringField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string contactPhoneString
    {
        get
        {
            return this.contactPhoneStringField;
        }
        set
        {
            this.contactPhoneStringField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string organizationNo
    {
        get
        {
            return this.organizationNoField;
        }
        set
        {
            this.organizationNoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemBuilding
{

    private string buildingTypeField;

    private string heatingTypeField;

    private string energyVentilationField;

    private string facadeField;

    private string roofField;

    private string loftFloorField;

    private string frameworkField;

    private string chimneyField;

    private string chimneypotField;

    private string municipalWaterField;

    private string metalworkField;

    private string foundationField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string buildingType
    {
        get
        {
            return this.buildingTypeField;
        }
        set
        {
            this.buildingTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string heatingType
    {
        get
        {
            return this.heatingTypeField;
        }
        set
        {
            this.heatingTypeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string energyVentilation
    {
        get
        {
            return this.energyVentilationField;
        }
        set
        {
            this.energyVentilationField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string facade
    {
        get
        {
            return this.facadeField;
        }
        set
        {
            this.facadeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string roof
    {
        get
        {
            return this.roofField;
        }
        set
        {
            this.roofField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string loftFloor
    {
        get
        {
            return this.loftFloorField;
        }
        set
        {
            this.loftFloorField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string framework
    {
        get
        {
            return this.frameworkField;
        }
        set
        {
            this.frameworkField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string chimney
    {
        get
        {
            return this.chimneyField;
        }
        set
        {
            this.chimneyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string chimneypot
    {
        get
        {
            return this.chimneypotField;
        }
        set
        {
            this.chimneypotField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string municipalWater
    {
        get
        {
            return this.municipalWaterField;
        }
        set
        {
            this.municipalWaterField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string metalwork
    {
        get
        {
            return this.metalworkField;
        }
        set
        {
            this.metalworkField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string foundation
    {
        get
        {
            return this.foundationField;
        }
        set
        {
            this.foundationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemRealtorsRealtor
{

    private string idField;

    private string firstnameField;

    private string lastnameField;

    private string typeField;

    private string emailField;

    private string phoneField;

    private string phoneStringField;

    private string cellphoneField;

    private string cellphoneStringField;

    private string imageField;

    private string titleField;

    private string titleExtraField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string firstname
    {
        get
        {
            return this.firstnameField;
        }
        set
        {
            this.firstnameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lastname
    {
        get
        {
            return this.lastnameField;
        }
        set
        {
            this.lastnameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string email
    {
        get
        {
            return this.emailField;
        }
        set
        {
            this.emailField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string phone
    {
        get
        {
            return this.phoneField;
        }
        set
        {
            this.phoneField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string phoneString
    {
        get
        {
            return this.phoneStringField;
        }
        set
        {
            this.phoneStringField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cellphone
    {
        get
        {
            return this.cellphoneField;
        }
        set
        {
            this.cellphoneField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string cellphoneString
    {
        get
        {
            return this.cellphoneStringField;
        }
        set
        {
            this.cellphoneStringField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string image
    {
        get
        {
            return this.imageField;
        }
        set
        {
            this.imageField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string title
    {
        get
        {
            return this.titleField;
        }
        set
        {
            this.titleField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string titleExtra
    {
        get
        {
            return this.titleExtraField;
        }
        set
        {
            this.titleExtraField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemShowings
{

    private ItemShowingsShowing[] showingField;

    private string noShowingDefaultTextField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Showing", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemShowingsShowing[] Showing
    {
        get
        {
            return this.showingField;
        }
        set
        {
            this.showingField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string noShowingDefaultText
    {
        get
        {
            return this.noShowingDefaultTextField;
        }
        set
        {
            this.noShowingDefaultTextField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemShowingsShowing
{

    private ItemShowingsShowingSlots[] slotsField;

    private string idField;

    private string startDateField;

    private string endDateField;

    private string commentField;

    private string hideStartTimeField;

    private string hideEndTimeField;

    private string fullyBookedField;

    private string openForRegistrationField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Slots", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemShowingsShowingSlots[] Slots
    {
        get
        {
            return this.slotsField;
        }
        set
        {
            this.slotsField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string startDate
    {
        get
        {
            return this.startDateField;
        }
        set
        {
            this.startDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string endDate
    {
        get
        {
            return this.endDateField;
        }
        set
        {
            this.endDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string comment
    {
        get
        {
            return this.commentField;
        }
        set
        {
            this.commentField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hideStartTime
    {
        get
        {
            return this.hideStartTimeField;
        }
        set
        {
            this.hideStartTimeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string hideEndTime
    {
        get
        {
            return this.hideEndTimeField;
        }
        set
        {
            this.hideEndTimeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string fullyBooked
    {
        get
        {
            return this.fullyBookedField;
        }
        set
        {
            this.fullyBookedField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string openForRegistration
    {
        get
        {
            return this.openForRegistrationField;
        }
        set
        {
            this.openForRegistrationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemShowingsShowingSlots
{

    private ItemShowingsShowingSlotsSlot[] slotField;

    private string publishedSlotsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Slot", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemShowingsShowingSlotsSlot[] Slot
    {
        get
        {
            return this.slotField;
        }
        set
        {
            this.slotField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string publishedSlots
    {
        get
        {
            return this.publishedSlotsField;
        }
        set
        {
            this.publishedSlotsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemShowingsShowingSlotsSlot
{

    private string idField;

    private string startDateField;

    private string endDateField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string startDate
    {
        get
        {
            return this.startDateField;
        }
        set
        {
            this.startDateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string endDate
    {
        get
        {
            return this.endDateField;
        }
        set
        {
            this.endDateField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemBids
{

    private string policyField;

    private string startedField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string policy
    {
        get
        {
            return this.policyField;
        }
        set
        {
            this.policyField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string started
    {
        get
        {
            return this.startedField;
        }
        set
        {
            this.startedField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemServitudes
{

    private string commentField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string comment
    {
        get
        {
            return this.commentField;
        }
        set
        {
            this.commentField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemImagesImage
{

    private ItemImagesImageHighres[] highresField;

    private ItemImagesImageLarge[] largeField;

    private ItemImagesImageMedium[] mediumField;

    private ItemImagesImageSmall[] smallField;

    private ItemImagesImageResize[] resizeField;

    private string idField;

    private string textField;

    private string categoryField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Highres", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemImagesImageHighres[] Highres
    {
        get
        {
            return this.highresField;
        }
        set
        {
            this.highresField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Large", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemImagesImageLarge[] Large
    {
        get
        {
            return this.largeField;
        }
        set
        {
            this.largeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Medium", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemImagesImageMedium[] Medium
    {
        get
        {
            return this.mediumField;
        }
        set
        {
            this.mediumField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Small", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemImagesImageSmall[] Small
    {
        get
        {
            return this.smallField;
        }
        set
        {
            this.smallField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Resize", Form = System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemImagesImageResize[] Resize
    {
        get
        {
            return this.resizeField;
        }
        set
        {
            this.resizeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string text
    {
        get
        {
            return this.textField;
        }
        set
        {
            this.textField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string category
    {
        get
        {
            return this.categoryField;
        }
        set
        {
            this.categoryField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemImagesImageHighres
{

    private string pathField;

    private string sizeField;

    private string widthField;

    private string heightField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string path
    {
        get
        {
            return this.pathField;
        }
        set
        {
            this.pathField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string size
    {
        get
        {
            return this.sizeField;
        }
        set
        {
            this.sizeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string width
    {
        get
        {
            return this.widthField;
        }
        set
        {
            this.widthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string height
    {
        get
        {
            return this.heightField;
        }
        set
        {
            this.heightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemImagesImageLarge
{

    private string pathField;

    private string sizeField;

    private string widthField;

    private string heightField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string path
    {
        get
        {
            return this.pathField;
        }
        set
        {
            this.pathField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string size
    {
        get
        {
            return this.sizeField;
        }
        set
        {
            this.sizeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string width
    {
        get
        {
            return this.widthField;
        }
        set
        {
            this.widthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string height
    {
        get
        {
            return this.heightField;
        }
        set
        {
            this.heightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemImagesImageMedium
{

    private string pathField;

    private string sizeField;

    private string widthField;

    private string heightField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string path
    {
        get
        {
            return this.pathField;
        }
        set
        {
            this.pathField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string size
    {
        get
        {
            return this.sizeField;
        }
        set
        {
            this.sizeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string width
    {
        get
        {
            return this.widthField;
        }
        set
        {
            this.widthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string height
    {
        get
        {
            return this.heightField;
        }
        set
        {
            this.heightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemImagesImageSmall
{

    private string pathField;

    private string sizeField;

    private string widthField;

    private string heightField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string path
    {
        get
        {
            return this.pathField;
        }
        set
        {
            this.pathField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string size
    {
        get
        {
            return this.sizeField;
        }
        set
        {
            this.sizeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string width
    {
        get
        {
            return this.widthField;
        }
        set
        {
            this.widthField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string height
    {
        get
        {
            return this.heightField;
        }
        set
        {
            this.heightField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemImagesImageResize
{

    private string pathField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string path
    {
        get
        {
            return this.pathField;
        }
        set
        {
            this.pathField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemMediaMediaItem
{

    private string aliasField;

    private string urlField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string alias
    {
        get
        {
            return this.aliasField;
        }
        set
        {
            this.aliasField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string url
    {
        get
        {
            return this.urlField;
        }
        set
        {
            this.urlField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemObjectDocumentsObjectDocument
{

    private string aliasField;

    private string filesizeField;

    private string hrefField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string alias
    {
        get
        {
            return this.aliasField;
        }
        set
        {
            this.aliasField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string filesize
    {
        get
        {
            return this.filesizeField;
        }
        set
        {
            this.filesizeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string href
    {
        get
        {
            return this.hrefField;
        }
        set
        {
            this.hrefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemApartmentCooperativeDocumentsApartmentCooperativeDocument
{

    private string aliasField;

    private string filesizeField;

    private string hrefField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string alias
    {
        get
        {
            return this.aliasField;
        }
        set
        {
            this.aliasField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string filesize
    {
        get
        {
            return this.filesizeField;
        }
        set
        {
            this.filesizeField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string href
    {
        get
        {
            return this.hrefField;
        }
        set
        {
            this.hrefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemOffice
{

    private string idField;

    private string nameField;

    private string xCoordinateField;

    private string yCoordinateField;

    private string latField;

    private string lonField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string xCoordinate
    {
        get
        {
            return this.xCoordinateField;
        }
        set
        {
            this.xCoordinateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string yCoordinate
    {
        get
        {
            return this.yCoordinateField;
        }
        set
        {
            this.yCoordinateField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lat
    {
        get
        {
            return this.latField;
        }
        set
        {
            this.latField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string lon
    {
        get
        {
            return this.lonField;
        }
        set
        {
            this.lonField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemCorporation
{

    private string idField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string id
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemStatus
{

    private string horseFarmField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string horseFarm
    {
        get
        {
            return this.horseFarmField;
        }
        set
        {
            this.horseFarmField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
public partial class ItemMeta
{

    private string keywordsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string keywords
    {
        get
        {
            return this.keywordsField;
        }
        set
        {
            this.keywordsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
public partial class NewDataSet
{

    private Item[] itemsField;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Item")]
    public Item[] Items
    {
        get
        {
            return this.itemsField;
        }
        set
        {
            this.itemsField = value;
        }
    }
}
}