//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SlutPriserModel", "FK_Images_Properties", "Properties", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(SlutPriser.Properties), "Images", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(SlutPriser.Images), true)]

#endregion

namespace SlutPriser
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SlutPriserEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SlutPriserEntities object using the connection string found in the 'SlutPriserEntities' section of the application configuration file.
        /// </summary>
        public SlutPriserEntities() : base("name=SlutPriserEntities", "SlutPriserEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SlutPriserEntities object.
        /// </summary>
        public SlutPriserEntities(string connectionString) : base(connectionString, "SlutPriserEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SlutPriserEntities object.
        /// </summary>
        public SlutPriserEntities(EntityConnection connection) : base(connection, "SlutPriserEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Images> Images
        {
            get
            {
                if ((_Images == null))
                {
                    _Images = base.CreateObjectSet<Images>("Images");
                }
                return _Images;
            }
        }
        private ObjectSet<Images> _Images;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Properties> Properties
        {
            get
            {
                if ((_Properties == null))
                {
                    _Properties = base.CreateObjectSet<Properties>("Properties");
                }
                return _Properties;
            }
        }
        private ObjectSet<Properties> _Properties;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SoldProperties> SoldProperties
        {
            get
            {
                if ((_SoldProperties == null))
                {
                    _SoldProperties = base.CreateObjectSet<SoldProperties>("SoldProperties");
                }
                return _SoldProperties;
            }
        }
        private ObjectSet<SoldProperties> _SoldProperties;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Images EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToImages(Images images)
        {
            base.AddObject("Images", images);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Properties EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProperties(Properties properties)
        {
            base.AddObject("Properties", properties);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SoldProperties EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSoldProperties(SoldProperties soldProperties)
        {
            base.AddObject("SoldProperties", soldProperties);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SlutPriserModel", Name="Images")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Images : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Images object.
        /// </summary>
        /// <param name="property">Initial value of the Property property.</param>
        /// <param name="location">Initial value of the Location property.</param>
        /// <param name="id">Initial value of the Id property.</param>
        public static Images CreateImages(global::System.String property, global::System.String location, global::System.Int32 id)
        {
            Images images = new Images();
            images.Property = property;
            images.Location = location;
            images.Id = id;
            return images;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Property
        {
            get
            {
                return _Property;
            }
            set
            {
                OnPropertyChanging(value);
                ReportPropertyChanging("Property");
                _Property = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Property");
                OnPropertyChanged();
            }
        }
        private global::System.String _Property;
        partial void OnPropertyChanging(global::System.String value);
        partial void OnPropertyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Location
        {
            get
            {
                return _Location;
            }
            set
            {
                OnLocationChanging(value);
                ReportPropertyChanging("Location");
                _Location = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Location");
                OnLocationChanged();
            }
        }
        private global::System.String _Location;
        partial void OnLocationChanging(global::System.String value);
        partial void OnLocationChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SlutPriserModel", "FK_Images_Properties", "Properties")]
        public Properties Properties
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Properties>("SlutPriserModel.FK_Images_Properties", "Properties").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Properties>("SlutPriserModel.FK_Images_Properties", "Properties").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Properties> PropertiesReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Properties>("SlutPriserModel.FK_Images_Properties", "Properties");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Properties>("SlutPriserModel.FK_Images_Properties", "Properties", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SlutPriserModel", Name="Properties")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Properties : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Properties object.
        /// </summary>
        /// <param name="key">Initial value of the Key property.</param>
        /// <param name="type">Initial value of the Type property.</param>
        /// <param name="area1">Initial value of the Area1 property.</param>
        /// <param name="rooms">Initial value of the Rooms property.</param>
        /// <param name="rent">Initial value of the Rent property.</param>
        /// <param name="listingPrice">Initial value of the ListingPrice property.</param>
        /// <param name="operatingCost">Initial value of the OperatingCost property.</param>
        /// <param name="buildYear">Initial value of the BuildYear property.</param>
        public static Properties CreateProperties(global::System.String key, global::System.String type, global::System.String area1, global::System.Int32 rooms, global::System.Int32 rent, global::System.Int32 listingPrice, global::System.Int32 operatingCost, global::System.Int32 buildYear)
        {
            Properties properties = new Properties();
            properties.Key = key;
            properties.Type = type;
            properties.Area1 = area1;
            properties.Rooms = rooms;
            properties.Rent = rent;
            properties.ListingPrice = listingPrice;
            properties.OperatingCost = operatingCost;
            properties.BuildYear = buildYear;
            return properties;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Key
        {
            get
            {
                return _Key;
            }
            set
            {
                if (_Key != value)
                {
                    OnKeyChanging(value);
                    ReportPropertyChanging("Key");
                    _Key = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Key");
                    OnKeyChanged();
                }
            }
        }
        private global::System.String _Key;
        partial void OnKeyChanging(global::System.String value);
        partial void OnKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Area
        {
            get
            {
                return _Area;
            }
            set
            {
                OnAreaChanging(value);
                ReportPropertyChanging("Area");
                _Area = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Area");
                OnAreaChanged();
            }
        }
        private Nullable<global::System.Double> _Area;
        partial void OnAreaChanging(Nullable<global::System.Double> value);
        partial void OnAreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Area1
        {
            get
            {
                return _Area1;
            }
            set
            {
                OnArea1Changing(value);
                ReportPropertyChanging("Area1");
                _Area1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Area1");
                OnArea1Changed();
            }
        }
        private global::System.String _Area1;
        partial void OnArea1Changing(global::System.String value);
        partial void OnArea1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Area2
        {
            get
            {
                return _Area2;
            }
            set
            {
                OnArea2Changing(value);
                ReportPropertyChanging("Area2");
                _Area2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Area2");
                OnArea2Changed();
            }
        }
        private global::System.String _Area2;
        partial void OnArea2Changing(global::System.String value);
        partial void OnArea2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Rooms
        {
            get
            {
                return _Rooms;
            }
            set
            {
                OnRoomsChanging(value);
                ReportPropertyChanging("Rooms");
                _Rooms = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rooms");
                OnRoomsChanged();
            }
        }
        private global::System.Int32 _Rooms;
        partial void OnRoomsChanging(global::System.Int32 value);
        partial void OnRoomsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Rent
        {
            get
            {
                return _Rent;
            }
            set
            {
                OnRentChanging(value);
                ReportPropertyChanging("Rent");
                _Rent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rent");
                OnRentChanged();
            }
        }
        private global::System.Int32 _Rent;
        partial void OnRentChanging(global::System.Int32 value);
        partial void OnRentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ListingPrice
        {
            get
            {
                return _ListingPrice;
            }
            set
            {
                OnListingPriceChanging(value);
                ReportPropertyChanging("ListingPrice");
                _ListingPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ListingPrice");
                OnListingPriceChanged();
            }
        }
        private global::System.Int32 _ListingPrice;
        partial void OnListingPriceChanging(global::System.Int32 value);
        partial void OnListingPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OperatingCost
        {
            get
            {
                return _OperatingCost;
            }
            set
            {
                OnOperatingCostChanging(value);
                ReportPropertyChanging("OperatingCost");
                _OperatingCost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OperatingCost");
                OnOperatingCostChanged();
            }
        }
        private global::System.Int32 _OperatingCost;
        partial void OnOperatingCostChanging(global::System.Int32 value);
        partial void OnOperatingCostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 BuildYear
        {
            get
            {
                return _BuildYear;
            }
            set
            {
                OnBuildYearChanging(value);
                ReportPropertyChanging("BuildYear");
                _BuildYear = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BuildYear");
                OnBuildYearChanged();
            }
        }
        private global::System.Int32 _BuildYear;
        partial void OnBuildYearChanging(global::System.Int32 value);
        partial void OnBuildYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FinalPrice
        {
            get
            {
                return _FinalPrice;
            }
            set
            {
                OnFinalPriceChanging(value);
                ReportPropertyChanging("FinalPrice");
                _FinalPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FinalPrice");
                OnFinalPriceChanged();
            }
        }
        private Nullable<global::System.Int32> _FinalPrice;
        partial void OnFinalPriceChanging(Nullable<global::System.Int32> value);
        partial void OnFinalPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> ListingDate
        {
            get
            {
                return _ListingDate;
            }
            set
            {
                OnListingDateChanging(value);
                ReportPropertyChanging("ListingDate");
                _ListingDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ListingDate");
                OnListingDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _ListingDate;
        partial void OnListingDateChanging(Nullable<global::System.DateTime> value);
        partial void OnListingDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SellingDate
        {
            get
            {
                return _SellingDate;
            }
            set
            {
                OnSellingDateChanging(value);
                ReportPropertyChanging("SellingDate");
                _SellingDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SellingDate");
                OnSellingDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _SellingDate;
        partial void OnSellingDateChanging(Nullable<global::System.DateTime> value);
        partial void OnSellingDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ListingPricePerArea
        {
            get
            {
                return _ListingPricePerArea;
            }
            set
            {
                OnListingPricePerAreaChanging(value);
                ReportPropertyChanging("ListingPricePerArea");
                _ListingPricePerArea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ListingPricePerArea");
                OnListingPricePerAreaChanged();
            }
        }
        private Nullable<global::System.Int32> _ListingPricePerArea;
        partial void OnListingPricePerAreaChanging(Nullable<global::System.Int32> value);
        partial void OnListingPricePerAreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Broker
        {
            get
            {
                return _Broker;
            }
            set
            {
                OnBrokerChanging(value);
                ReportPropertyChanging("Broker");
                _Broker = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Broker");
                OnBrokerChanged();
            }
        }
        private global::System.String _Broker;
        partial void OnBrokerChanging(global::System.String value);
        partial void OnBrokerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> BiArea
        {
            get
            {
                return _BiArea;
            }
            set
            {
                OnBiAreaChanging(value);
                ReportPropertyChanging("BiArea");
                _BiArea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BiArea");
                OnBiAreaChanged();
            }
        }
        private Nullable<global::System.Double> _BiArea;
        partial void OnBiAreaChanging(Nullable<global::System.Double> value);
        partial void OnBiAreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PlotArea
        {
            get
            {
                return _PlotArea;
            }
            set
            {
                OnPlotAreaChanging(value);
                ReportPropertyChanging("PlotArea");
                _PlotArea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PlotArea");
                OnPlotAreaChanged();
            }
        }
        private Nullable<global::System.Double> _PlotArea;
        partial void OnPlotAreaChanging(Nullable<global::System.Double> value);
        partial void OnPlotAreaChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SlutPriserModel", "FK_Images_Properties", "Images")]
        public EntityCollection<Images> Images
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Images>("SlutPriserModel.FK_Images_Properties", "Images");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Images>("SlutPriserModel.FK_Images_Properties", "Images", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SlutPriserModel", Name="SoldProperties")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SoldProperties : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SoldProperties object.
        /// </summary>
        /// <param name="key">Initial value of the Key property.</param>
        /// <param name="area">Initial value of the Area property.</param>
        /// <param name="area1">Initial value of the Area1 property.</param>
        /// <param name="city">Initial value of the City property.</param>
        /// <param name="rooms">Initial value of the Rooms property.</param>
        /// <param name="rent">Initial value of the Rent property.</param>
        /// <param name="operatingCost">Initial value of the OperatingCost property.</param>
        /// <param name="finalPrice">Initial value of the FinalPrice property.</param>
        public static SoldProperties CreateSoldProperties(global::System.String key, global::System.Double area, global::System.String area1, global::System.String city, global::System.Int32 rooms, global::System.Int32 rent, global::System.Int32 operatingCost, global::System.Int32 finalPrice)
        {
            SoldProperties soldProperties = new SoldProperties();
            soldProperties.Key = key;
            soldProperties.Area = area;
            soldProperties.Area1 = area1;
            soldProperties.City = city;
            soldProperties.Rooms = rooms;
            soldProperties.Rent = rent;
            soldProperties.OperatingCost = operatingCost;
            soldProperties.FinalPrice = finalPrice;
            return soldProperties;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Key
        {
            get
            {
                return _Key;
            }
            set
            {
                if (_Key != value)
                {
                    OnKeyChanging(value);
                    ReportPropertyChanging("Key");
                    _Key = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Key");
                    OnKeyChanged();
                }
            }
        }
        private global::System.String _Key;
        partial void OnKeyChanging(global::System.String value);
        partial void OnKeyChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private global::System.String _Type;
        partial void OnTypeChanging(global::System.String value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double Area
        {
            get
            {
                return _Area;
            }
            set
            {
                OnAreaChanging(value);
                ReportPropertyChanging("Area");
                _Area = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Area");
                OnAreaChanged();
            }
        }
        private global::System.Double _Area;
        partial void OnAreaChanging(global::System.Double value);
        partial void OnAreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Area1
        {
            get
            {
                return _Area1;
            }
            set
            {
                OnArea1Changing(value);
                ReportPropertyChanging("Area1");
                _Area1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Area1");
                OnArea1Changed();
            }
        }
        private global::System.String _Area1;
        partial void OnArea1Changing(global::System.String value);
        partial void OnArea1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Area2
        {
            get
            {
                return _Area2;
            }
            set
            {
                OnArea2Changing(value);
                ReportPropertyChanging("Area2");
                _Area2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Area2");
                OnArea2Changed();
            }
        }
        private global::System.String _Area2;
        partial void OnArea2Changing(global::System.String value);
        partial void OnArea2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String City
        {
            get
            {
                return _City;
            }
            set
            {
                OnCityChanging(value);
                ReportPropertyChanging("City");
                _City = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("City");
                OnCityChanged();
            }
        }
        private global::System.String _City;
        partial void OnCityChanging(global::System.String value);
        partial void OnCityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Rooms
        {
            get
            {
                return _Rooms;
            }
            set
            {
                OnRoomsChanging(value);
                ReportPropertyChanging("Rooms");
                _Rooms = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rooms");
                OnRoomsChanged();
            }
        }
        private global::System.Int32 _Rooms;
        partial void OnRoomsChanging(global::System.Int32 value);
        partial void OnRoomsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Rent
        {
            get
            {
                return _Rent;
            }
            set
            {
                OnRentChanging(value);
                ReportPropertyChanging("Rent");
                _Rent = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Rent");
                OnRentChanged();
            }
        }
        private global::System.Int32 _Rent;
        partial void OnRentChanging(global::System.Int32 value);
        partial void OnRentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 OperatingCost
        {
            get
            {
                return _OperatingCost;
            }
            set
            {
                OnOperatingCostChanging(value);
                ReportPropertyChanging("OperatingCost");
                _OperatingCost = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OperatingCost");
                OnOperatingCostChanged();
            }
        }
        private global::System.Int32 _OperatingCost;
        partial void OnOperatingCostChanging(global::System.Int32 value);
        partial void OnOperatingCostChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BuildYear
        {
            get
            {
                return _BuildYear;
            }
            set
            {
                OnBuildYearChanging(value);
                ReportPropertyChanging("BuildYear");
                _BuildYear = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BuildYear");
                OnBuildYearChanged();
            }
        }
        private Nullable<global::System.Int32> _BuildYear;
        partial void OnBuildYearChanging(Nullable<global::System.Int32> value);
        partial void OnBuildYearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FinalPrice
        {
            get
            {
                return _FinalPrice;
            }
            set
            {
                OnFinalPriceChanging(value);
                ReportPropertyChanging("FinalPrice");
                _FinalPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FinalPrice");
                OnFinalPriceChanged();
            }
        }
        private global::System.Int32 _FinalPrice;
        partial void OnFinalPriceChanging(global::System.Int32 value);
        partial void OnFinalPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> SellingDate
        {
            get
            {
                return _SellingDate;
            }
            set
            {
                OnSellingDateChanging(value);
                ReportPropertyChanging("SellingDate");
                _SellingDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SellingDate");
                OnSellingDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _SellingDate;
        partial void OnSellingDateChanging(Nullable<global::System.DateTime> value);
        partial void OnSellingDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ListingPricePerArea
        {
            get
            {
                return _ListingPricePerArea;
            }
            set
            {
                OnListingPricePerAreaChanging(value);
                ReportPropertyChanging("ListingPricePerArea");
                _ListingPricePerArea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ListingPricePerArea");
                OnListingPricePerAreaChanged();
            }
        }
        private Nullable<global::System.Int32> _ListingPricePerArea;
        partial void OnListingPricePerAreaChanging(Nullable<global::System.Int32> value);
        partial void OnListingPricePerAreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Broker
        {
            get
            {
                return _Broker;
            }
            set
            {
                OnBrokerChanging(value);
                ReportPropertyChanging("Broker");
                _Broker = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Broker");
                OnBrokerChanged();
            }
        }
        private global::System.String _Broker;
        partial void OnBrokerChanging(global::System.String value);
        partial void OnBrokerChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Address
        {
            get
            {
                return _Address;
            }
            set
            {
                OnAddressChanging(value);
                ReportPropertyChanging("Address");
                _Address = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Address");
                OnAddressChanged();
            }
        }
        private global::System.String _Address;
        partial void OnAddressChanging(global::System.String value);
        partial void OnAddressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> BiArea
        {
            get
            {
                return _BiArea;
            }
            set
            {
                OnBiAreaChanging(value);
                ReportPropertyChanging("BiArea");
                _BiArea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BiArea");
                OnBiAreaChanged();
            }
        }
        private Nullable<global::System.Double> _BiArea;
        partial void OnBiAreaChanging(Nullable<global::System.Double> value);
        partial void OnBiAreaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PlotArea
        {
            get
            {
                return _PlotArea;
            }
            set
            {
                OnPlotAreaChanging(value);
                ReportPropertyChanging("PlotArea");
                _PlotArea = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PlotArea");
                OnPlotAreaChanged();
            }
        }
        private Nullable<global::System.Double> _PlotArea;
        partial void OnPlotAreaChanging(Nullable<global::System.Double> value);
        partial void OnPlotAreaChanged();

        #endregion

    
    }

    #endregion

    
}
